---

- name: Verify play
  hosts: all
  tasks:
    - name: Install redis from epel repository for testing
      yum:
        name: redis
        state: present
        update_cache: true
        enablerepo: epel

    - name: Remove redis package
      yum:
        name: redis
        state: absent
